Deprecate autostep in RHEL8
pykickstart/pykickstart pull request #343
Opened 2020-10-22 13:31 UTC by VladimirSlavik

It doesn't really work anymore.

2020-10-22 13:32 UTC, VladimirSlavik commented
Only as draft because it's not clear yet if we will do this.

2020-11-09 14:27 UTC, VladimirSlavik reviewed
After landing the F34 changes in #344, some errors in this are apparent.

2020-11-09 14:27 UTC, VladimirSlavik commented on tests/commands/autostep.py
> +from pykickstart.commands.autostep import FC3_AutoStep, RHEL8_AutoStep
No need to import `RHEL8_AutoStep`

2020-11-09 14:27 UTC, VladimirSlavik commented on pykickstart/commands/autostep.py
> +from pykickstart.version import FC3, RHEL8
Import `versionToLongString` here.

2021-01-11 15:29 UTC, VladimirSlavik commented
It seems to me that Pylint got upgraded in Travis (with new Ubuntu that they warned of), the errors don't look to me like "mine".

2021-01-14 17:12 UTC, VladimirSlavik commented
@bcl this is blocked by #371, right?

2021-01-14 18:41 UTC, bcl commented
Not really, I can run the tests locally before merging. But it does need a rhbz with acks.

2021-05-13 15:19 UTC, bcl requested changes
Rebase this PR on the current rhel8-branch so that the new GH Action based tests run.

The Commit message also needs a Resolves: rhbz#1895951 line added to it.

2021-05-13 17:53 UTC, merged

2021-05-13 18:34 UTC, VladimirSlavik commented
Thanks!