Deprecate the %traceback section
pykickstart/pykickstart pull request #351
Opened 2020-11-10 18:51 UTC by VladimirSlavik

It only duplicates the `%onerror` section and exists due to historical reasons.

2020-11-11 14:44 UTC, poncovka approved these changes
Looks good to me. Thanks!

2020-11-12 11:38 UTC, jkonecny12 approved these changes
LGTM! Thanks for cleaning-up our old API!

2020-11-12 16:39 UTC, bcl requested changes
Please add a test for this

2020-11-24 15:24 UTC, VladimirSlavik commented
Tests added...

2020-11-30 23:17 UTC, bcl commented
Dropped a couple unused imports from the test and merged to master. Thanks!

2020-11-30 23:17 UTC, closed without merging