commands: Add missing DeprecatedCommand class to RHEL10_Module
pykickstart/pykickstart pull request #495
Opened 2024-07-03 12:49 UTC by KKoukiou

Also increase consistently with other deprecated commands, by calling the DeprecatedCommand init, instead of the custom parser.

2024-07-03 12:51 UTC, KKoukiou commented
I just noticed that the module is missing the DeprecatedCommand. I am not sure where it's used, but I today [switched some of Anaconda tests](https://github.com/rhinstaller/anaconda/pull/5741) to rely on RemovedCommand for some skipping. So let's be correct.

2024-07-23 16:11 UTC, bcl requested changes

2024-07-23 16:11 UTC, bcl commented on tests/commands/module.py
> +        self.assertEqual(issubclass(parser.__class__, DeprecatedCommand), True)
You need to import `DeprecatedCommand` and drop the `KickstartDeprecationWarning` import.

2024-08-08 21:40 UTC, bcl approved these changes
Looks good, thanks!

2024-08-08 21:41 UTC, merged