[WIP] add support for home reuse to autopart
pykickstart/pykickstart pull request #499
Opened 2024-08-05 08:04 UTC by rvykydal

2024-08-05 14:49 UTC, bcl commented on pykickstart/commands/autopart.py
> +                        Specifies which existing mountpoins should be
I would assume this is non-recursive, right? May want to make a note of that just to be clear that erasing / doesn't also erase /home if it is a separate mountpoint.

2024-08-05 16:36 UTC, bcl commented
I'm not opposed to this, but I also wonder if there is another way? Would it instead make it clearer if `part` were used to set the behavior for the mountpoints? Also, how does it identify the previous mounting locations of various devices reliably?

The failed tests were unrelated, I've just fixed those on master so a rebase will take care of them.

2024-08-08 21:43 UTC, Conan-Kudo requested changes

2024-08-08 21:43 UTC, Conan-Kudo commented on pykickstart/commands/autopart.py
> +                        Specifies which existing mountpoins should be
`mountpoins` -> `mountpoints`

2024-09-03 07:24 UTC, rvykydal commented
> I'm not opposed to this, but I also wonder if there is another way? Would it instead make it clearer if `part` were used to set the behavior for the mountpoints? Also, how does it identify the previous mounting locations of various devices reliably?

The approach is described in https://github.com/rhinstaller/anaconda/pull/5814
It is using *ExistingSystems DeviceTree API to find existing installations and therefore mount points. And automatic partitioning request structure to define what to do (pass reuse/erasse/remove requests to the autopartitioning).
Our (initial?) use case is limited to single Linux system (perhaps even single system).
It is possible that we would support multiple systems and selection in the UI. Then passing mount points would be ambigous, so we'd need to pass respective (selected) devices to the backend - in that case this kickstart api would really make less sense. (We could maybe allow --reuse /home:DEVNAME then, but it would require more thinking). Overall it seems to me for more complicated / ambigous use cases users should rather use mount point assignment. We should just offer simple use case valuable for most of the users here.

2025-01-08 13:45 UTC, closed without merging